### ISSUE TITLE
ReferenceError: "AdminDirectory" har inte definierats

### ISSUE THREAD

**Issue by riccla0321** [scouternasetjanster/Google-Scoutnet-synk#1]
Får detta error när jag försöker implementera skriptet. Vad kan man göra åt det?

Starta | Funktion | Felmeddelande | Utlösare | Sluta
-- | -- | -- | -- | --
2018-04-25 18:18 | AccountsAndGroups | ReferenceError: "AdminDirectory" har inte definierats. (rad: 263, fil: Användare) | time-based | 2018-04-25 18:18

**Comment by riccla0321** [comment]
Efter att ha aktiverat dom så får jag detta:

Starta | Funktion | Felmeddelande | Utlösare | Sluta
-- | -- | -- | -- | --
2018-04-25 23:18 | AccountsAndGroups | Insufficient Permission (rad: 263, fil: Användare) | time-based | 2018-04-25 23:18

**Comment by webbmastern** [comment]
Har du tillräckliga behörigheter på ditt konto?
Då du kommer ge programmet befogenhet att tex skapa och ändra konton så behövs en hög behörighet, tex avancerad administratör / superadmin

**Comment by riccla0321** [comment]
Jag är "Avancerad administratör" och det finns inga andra administratörer (eller användare) i nuläget.

**Comment by webbmastern** [comment]
Har du gjort steg1 i instruktionen samt ställt in rätt domän i början av filen Användare.gs?

**Comment by riccla0321** [comment]
Ja, båda stegen är utförda.

**Comment by webbmastern** [comment]
Har du aktiverat API:erna på https://console.cloud.google.com/apis/library?project också

**Comment by riccla0321** [comment]
Ja, det är gjort. Hittar ingen Admin Directory API där, så jag antar att den bara ska aktiveras under Resurser > Avancerade Google-tjänster på script.google.com.

![image](https://user-images.githubusercontent.com/6883083/39320897-b7f8acf8-4985-11e8-8eb4-ac570e892eb3.png)

**Comment by webbmastern** [comment]
Testa sök på "Admin SDK" och se om det fungerar då.

**Comment by riccla0321** [comment]
Aktiverade "Admin SDK" och får fortfarande samma fel.

Starta | Funktion | Felmeddelande | Utlösare | Sluta
-- | -- | -- | -- | --
2018-04-26 20:18 | AccountsAndGroups | Insufficient Permission (rad: 263, fil: Användare) | time-based | 2018-04-26 20:18

**Comment by webbmastern** [comment]
Då du inte har några användare innan undrar jag i så fall om du har konfigurerat domänen i Google Suite och inte använder någon testdomän just nu?
Kolla om du har skrivit domänen på rätt form utan www i början av filen "Användare.gs". Tex testscoutkar.se
Jag tror det kan dröja ett litet tag innan behörigheter ändras i systemet fullt ut, så testa köra programmet igen innan du gör något av nedanstående.
I funktionen "listAllUsers"  finns en variabel som heter "domain" (rad 414)  byt ut den domänen som står där mot din egen och testa köra bara den funktionen. Den gör typ samma sak som den som blev fel men är för testsyfte.

Om det inte fungerar kan du testa lägga till en användare i underorganisationen "Scoutnet" och sen testa igen, men gör det bara i fall det innan inte fungerade så vi vet var felet ligger.

**Comment by riccla0321** [comment]
> I funktionen "listAllUsers" finns en variabel som heter "domain" (rad 414) byt ut den domänen som står där mot din egen och testa köra bara den funktionen. Den gör typ samma sak som den som blev fel men är för testsyfte.

Testade ovanstående och funktionen "listAllUsers" genererar inga felmeddelanden.

Hur ska jag gå vidare?

**Comment by webbmastern** [comment]
Logga in till Adminkonsolen med ditt adminkonto och tryck på "Säkerhet".
Tryck på "API-referens", och tryck på kryssrutan för att "Aktivera API-åtkomst".

**Comment by riccla0321** [comment]
> Logga in till Adminkonsolen med ditt adminkonto och tryck på "Säkerhet".
Tryck på "API-referens", och tryck på kryssrutan för att "Aktivera API-åtkomst".

Redan aktiverat. 

![image](https://user-images.githubusercontent.com/6883083/39452752-b7fe305a-4cd3-11e8-873f-6aba1d679fcd.png)

**Comment by webbmastern** [comment]
Kan du ta en skärmdump på hur det ser ut under Arkiv-->Projektegenskaper-->Omfattningar

**Comment by riccla0321** [comment]
![image](https://user-images.githubusercontent.com/6883083/39466066-24098eb8-4d27-11e8-9b3b-5e377c25d9a8.png)

**Comment by webbmastern** [comment]
I filen Grupper.gs rad 6. Har du ställt in din domän där också?
Kontrollera oavsett att de är rättstavade i båda filerna då det fungerade att anropa funktionen listAllUsers när du skrev in din domän direkt i funktionen.

**Comment by riccla0321** [comment]
> Har du ställt in din domän där också?

Ja, det är rättstavat, och samma stavning på båda ställena.

**Comment by webbmastern** [comment]
Vad händer om du kör funktionen GetGoogleAccounts() direkt. Går det?
Det är i den funktionen som du får fel.

**Comment by riccla0321** [comment]
> Vad händer om du kör funktionen GetGoogleAccounts() direkt. Går det?
Det är i den funktionen som du får fel.

Fungerar utan problem.

**Comment by riccla0321** [comment]
Nu helt plötsligt funkar AccountsAndGroups. Alla användare dyker upp i organisationen.

Kan det bero på att jag körde funktionen manuellt? Tidigare har jag kört funktionerna med tidsstyrning (enligt punkt 11 under "Inställningar" i README.md), men nu testade jag att köra funktionen manuellt "Play"-knappen, och då fick jag respons direkt.

**Comment by webbmastern** [comment]
Det är nu löst efter att ha kört programmet en gång manuellt först.
