### ISSUE TITLE
Förtydligande av e-postlistor och behörigheter

### ISSUE THREAD

**Issue by fredrikbaberg** [scouternasetjanster/Google-Scoutnet-synk#10]
Skulle vilja ha lite fler exempel på hur grupper konfigureras i kalkylark.

Följande två fall är jag intresserad av, kanske är fler som söker svar på det:

- Mejllista till alla medlemmar, men begränsa så att endast vissa (t.ex. kårstyrelsen) får göra utskick på den listan. Det finns maillistor i Scoutnet med ID jag kan använda, men hur fyller jag i kalkylarket? Olika Scoutnet-id för **Kan skicka och ta emot**, **Kan skicka** och **Kan ta emot**?
- Kombinera olika Scoutnet-id för grupper, är det möjligt? Vi har scouter som går på fler avdelningar (men endast kan vara registrerade på en avdelning åt gången i Scoutnet), så jag försöker hitta en lösning på det med flera specialiserade mailinglistor i Scoutnet som då skulle kombineras på något sätt.

**Comment by webbmastern** [comment]
Hej,
Angående första punkten med att begränsa vilka som tillåts skicka mm kommer det komma i kommande version av programmet. Ska försöka skriva något bra till det. Koden för just den funktionaliteten är dock klar, så det borde inte dröja allt för länge med när nästa version släpps.

Funktionaliteten för att lägga ihop flera listor från Scoutnet till en i Google ser ut att finnas i nuvarande version av programmet. Ange helt enkelt ett listid och sen ett kommatecken och sen ett till listid osv...

Angående registreringen av medlemmar så att man är med på två avdelningar i mejlinglistor så är det egentligen en Scoutnetfråga. Det går dock att komma runt på ett lite jobbigt sätt om man önskar en mejlinglista för varje avdelning. För din mejlinglista i Scoutnet har du då först en regel för alla som är medlemmar på aktuell avdelning. För ledare som är med på flera avdelningar skapar du en till regel för samma mejlinglista som säger att man ska vara medlem på aktuell avdelning samt ha en specifik ledarroll.
För scouter som är med på flera avdelningar kan du skapa en patrull på avdelningen för varje enskild person som detta gäller för och sen lägga till personen som patrulledare. Detta då man inte behöver vara registrerad på en avdelning för att ha en roll på den. Du skapar sedan en ny regel i samma mejlinglista som säger att man ska vara medlem på aktuell avdelning samt har rollen som patrulledare.
Du har nu alltså tre regler för de som är aktiva på en avdelning, "medlemmar", ledare, samt patrulledare (ej primär avdelning)

Det bör gå att slå ihop reglerna för ledare/patrulledare till en om du vill, men det blir kanske inte lika överskådligt.

Hoppas det hjälpte lite

**Comment by fredrikbaberg** [comment]
> Hej,
> Angående första punkten med att begränsa vilka som tillåts skicka mm kommer det komma i kommande version av programmet. Ska försöka skriva något bra till det. Koden för just den funktionaliteten är dock klar, så det borde inte dröja allt för länge med när nästa version släpps.
> 
> Funktionaliteten för att lägga ihop flera listor från Scoutnet till en i Google ser ut att finnas i nuvarande version av programmet. Ange helt enkelt ett listid och sen ett kommatecken och sen ett till listid osv...
> 
> Angående registreringen av medlemmar så att man är med på två avdelningar i mejlinglistor så är det egentligen en Scoutnetfråga. Det går dock att komma runt på ett lite jobbigt sätt om man önskar en mejlinglista för varje avdelning. För din mejlinglista i Scoutnet har du då först en regel för alla som är medlemmar på aktuell avdelning. För ledare som är med på flera avdelningar skapar du en till regel för samma mejlinglista som säger att man ska vara medlem på aktuell avdelning samt ha en specifik ledarroll.
> För scouter som är med på flera avdelningar kan du skapa en patrull på avdelningen för varje enskild person som detta gäller för och sen lägga till personen som patrulledare. Detta då man inte behöver vara registrerad på en avdelning för att ha en roll på den. Du skapar sedan en ny regel i samma mejlinglista som säger att man ska vara medlem på aktuell avdelning samt har rollen som patrulledare.
> Du har nu alltså tre regler för de som är aktiva på en avdelning, "medlemmar", ledare, samt patrulledare (ej primär avdelning)
> 
> Det bör gå att slå ihop reglerna för ledare/patrulledare till en om du vill, men det blir kanske inte lika överskådligt.
> 
> Hoppas det hjälpte lite

Tack för ett bra svar.

Jag har nu testat att lägga ihop flera listor genom att skriva in `<listnummer1>,<listnummer2>` i kolumn `C` och `@` i kolumn `D`, men verkar inte få det att fungera. Samma listnummer har jag använt i två andra separata listor, och där stämmer det, men i den kombinerade listan följer endast medlemmar från listan som är inskriven först med.

När det gäller medlemmar som är på fler avdelningar så diskuterar vi i kåren hur vi ska hantera det för att hitta en lösning som inte komplicerar administration för mycket. Jag ska se om/hur vi får med lösningen du skrev.

**Comment by fredrikbaberg** [comment]
Hej,
Att kombinera listor verkar fungera någorlunda. Jag har haft något problem med att endast ena listan kom med, men skrev om och körde om scriptet så fungerade det.
Så det borde gå bra att stänga det här ärendet.

**Comment by webbmastern** [comment]
Hej,
I senaste versionen 1.2.0 gjordes det en uppdatering som jag hoppas förenklar en hel del med hur @ används då det nu likställs med att ange ett list-id från Scoutnet för att ange vilka mottagare/avsändare man önskar tillåta.

Hör gärna av dig om du skulle hitta någon bugg med kombineringen av listor.
//Emil
