### ISSUE TITLE
Endast personer med gsuite ska kunna skicka till lista, ska ej läggas till listan

### ISSUE THREAD

**Issue by hakankvist** [scouternasetjanster/Google-Scoutnet-synk#12]
Hej!

Jag har ett antal listor som som går till alla föräldrar på en avdelning, och en lista som går till alla adresser i kåren.

På något sätt vill jag få till att begränsa så att endast de som har  ett gsuite-konto ska kunna skicka till listan (jag la till @ i kan skicka/sync). Det fick då till följd att personer med ett gsuite-konto som INTE är med på listan från scoutnet blev tillagda i gruppen (med rollen manager).

Innebär det att dessa personer kommer få mailen som skickas till listan också (det vill jag inte :)

**Comment by hakankvist** [comment]
Är det något som går att göra?
Jag har inte helt förstått avsnittet: Begränsa åtkomst för att skicka och ta emot e-post.
Några konkreta exempel (gärna med bilder) hade gjort det mer lättilgängligt.

**Comment by hakankvist** [comment]
Jag svarar mig själv.

Det går utmärkt, när man lägger till @ i kan skicka/sync. De personer som blir tillagda som manager, kan skicka till listan men tar inte mot mail. Vilket jag antaligen hade förstått om jag läst dokumentationen några gånger till.

Jag kommer nog försöka skicka upp en patch som förtydligar dokumentationen så att även en trött hjärna förstår.

**Comment by mrManner** [comment]
Tack Håkan för att du utforskade, och tack igen om du förtydligar i dokumentationen :)

**Comment by webbmastern** [comment]
För bättre tydlighet gällande detta så kommer vid nästa release länk-knapparna i kalkylarket ändras så att för respektive lista kommer leda till en sida där man enkelt kan se för varje e-postadress om de kan skicka respektive ta emot e-post.
