### ISSUE TITLE
API-anrop till directory.users.list misslyckades med felet: Invalid Input: INVALID_OU_ID (line 426, file "Användare")

### ISSUE THREAD

**Issue by vattlescout** [scouternasetjanster/Google-Scoutnet-synk#13]
Skrev mail till Emil den 2019-09-27 med följande innehåll (klippt ut det jag anser är viktigt i frågan)... Vid behov går det att få se delar av min kod för felsökning - dock kommer API-nycklar att ändras efter hand i så fall...

**Felmeddelandet jag får är:**
> API-anrop till directory.users.list misslyckades med felet: Invalid Input:
> INVALID_OU_ID (line 426, file "Användare")

**Comment by mrManner** [comment]
Hm, utan att ha kikat mycket alls på detta: directory.users.list är ett 
Google-API, INVALID_OU_ID låter som att scriptet försöker använda en 
organisatorisk enhet som inte finns, eller som har ett namn/id som på 
något sätt är ogiltigt.

Hur ser din `userAccountConfig` ut? Default är:

```
var userAccountConfig = [
	{
	scoutnetListId: "1234",  //
	orgUnitPath: "Styrelsen" //om du skriver Ledare så är det egentligen underorganisationen /Scoutnet/Ledare
	},
	{
	scoutnetListId: "8&rule_id=9874 (Roverscouter), 1122 (Kassör)", //Rover
	orgUnitPath: "Kårfunk/Rover"
	},
	{
	scoutnetListId: "8 (Lurk)", //Ledare, Utmanare, Rover, Kårfunktionärer. Då alla roverscouter och kårkassören redan är med i en lista kommer de ej med här
	orgUnitPath: "Kårfunk/LURK"
	}
];
```

**Comment by vattlescout** [comment]
> Hm, utan att ha kikat mycket alls på detta: directory.users.list är ett Google-API, INVALID_OU_ID låter som att scriptet försöker använda en organisatorisk enhet som inte finns, eller som har ett namn/id som på något sätt är ogiltigt. Hur ser din `userAccountConfig` ut? Default är: ``` var userAccountConfig = [ { scoutnetListId: "1234", // orgUnitPath: "Styrelsen" //om du skriver Ledare så är det egentligen underorganisationen /Scoutnet/Ledare }, { scoutnetListId: "8&rule_id=9874 (Roverscouter), 1122 (Kassör)", //Rover orgUnitPath: "Kårfunk/Rover" }, { scoutnetListId: "8 (Lurk)", //Ledare, Utmanare, Rover, Kårfunktionärer. Då alla roverscouter och kårkassören redan är med i en lista kommer de ej med här orgUnitPath: "Kårfunk/LURK" } ]; ```
> […](#)
> On 10/01, vattlescout wrote: Skrev mail till Emil den 2019-09-27 med följande innehåll (klippt ut det jag anser är viktigt i frågan)... Vid behov går det att få se delar av min kod för felsökning - dock kommer API-nycklar att ändras efter hand i så fall... **Felmeddelandet jag får är:** > API-anrop till directory.users.list misslyckades med felet: Invalid Input: > INVALID_OU_ID (line 426, file "Användare") -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #13

var userAccountConfig = [
  {
    scoutnetListId: "3370",  //
    orgUnitPath: "Spårare"
  },
  {
   scoutnetListId: "3369", //Rover
   orgUnitPath: "Upptäckare"
  },
  {
   scoutnetListId: "3354", //Ledare, Utmanare, Rover, Kårfunktionärer. Då alla roverscouter och kårkassören redan är med i en lista kommer de ej med här
   orgUnitPath: "Äventyrare"
  }
];

**Comment by vattlescout** [comment]
Hittade eventuellt felet... :) Verkar som om jag inte kan läsa innantill trotts allt.... :-(

**Comment by mrManner** [comment]
Bra att det verkar ha löst sig! Lycka till, och återkom om det är något mer som krånglar :)
