### ISSUE TITLE
Google användare tas bort och läggs till vid varenda syncning

### ISSUE THREAD

**Issue by hakankvist** [scouternasetjanster/Google-Scoutnet-synk#7]
Vi har några användare som tas bort/läggs till vid varenda syncning. Samtliga användare med detta problem har en gmail-address.
För gmail-adresser, så ignoreras punkten, dvs namn.efternamn är samma som namnefternamn och n.a.m.n.e.f.t.e.r.n.a.m.n, allting hamnar i samma inbox.

I loggen Audit-loggen i administratörsappen så ser det ut så här (äldsta even överst, nyast längst ner)
fornamn.efternamn tas bort från lista
fornamnefternam läggs till lista

Detta upprepas varje dag. 
De adresser där vi sett detta problemet är anhörigadresser. Maillistorna synkas med tom synkinställning och begränsa åtkomst satt till: ALL_IN_DOMAIN_CAN_POST.

Tittar man i grupperna, så adresserna verkligen tillagda med "fornamnefternamn" i grupperna.

**Comment by hakankvist** [comment]
Vet inte om detta kan bero på om t.ex kontot ursprungligen skapades med formen "fornmanefternamn" och att man sen valt att använda "fornamn.efternamn".

Vi har i alla fall tillfälligt kommit runt problemet genom att justera punkterna för emailadresserna i scoutnet, i vårt fall tagit bort punkten, det löser vårt problem tillfälligt i alla fall tills nästa gång en sådan adress kommer in i systemet.

**Comment by webbmastern** [comment]
Vilka problem upplever medlemmarna eller kåren med dessa onödiga operationer förutom att de helt enkelt är onödiga?

**Comment by hakankvist** [comment]
Problemet är när man kollar i loggen för vad som har hänt på kontot att det dyker upp en massa skräp events. 

Detta syns väldigt tydligt om man användare Android appen Google Admin:
https://play.google.com/store/apps/details?id=com.google.android.apps.enterprise.cpanel&hl=en

Tittar i "Audit logs" här så dyker det upp en massa skräp pga av dessa användarna, det gör det svårare att se om det finns riktiga problem.

**Comment by webbmastern** [comment]
Detta ska nu vara löst i samband med v1.1.0
https://github.com/scouternasetjanster/Google-Scoutnet-synk/releases/tag/v1.1.0
